# Generated by Django 4.0.6 on 2022-07-11 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugtracker',
            fields=[
                ('program', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=20)),
                ('problem_summary', models.TextField()),
                ('reported_by', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
