# Generated by Django 4.0.6 on 2022-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
