# Generated by Django 4.0.6 on 2022-07-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_alter_bugtracker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtracker',
            old_name='id',
            new_name='program_report_number',
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='program',
            field=models.CharField(choices=[('vscode', 'VS Code'), ('pycharm', 'Pycharm'), ('sublime', 'Sublime Text'), ('sqlserver', 'SQL Server'), ('notepad++', 'Notepad ++'), ('outlook', 'Outlook')], default='vscode', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='report_type',
            field=models.CharField(choices=[('coding_error', 'Coding Error'), ('design_issue', 'Design Issue'), ('suggestion', 'Suggestion'), ('documentation', 'Documentation'), ('hardware', 'Hardware'), ('query', 'Query')], default='coding_error', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='reported_by',
            field=models.CharField(choices=[('praneeth', 'Praneeth'), ('shruthi', 'Shruthi')], default='praneeth', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('infectious', 'Infectious'), ('minor', 'Minor'), ('serious', 'Serious'), ('fatal', 'Fatal')], default='mild', max_length=20),
        ),
    ]
