# Generated by Django 4.0.6 on 2022-07-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_rename_id_bugtracker_program_report_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtracker',
            old_name='program_report_number',
            new_name='id',
        ),
    ]
