# Generated by Django 4.0.6 on 2022-07-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_rename_program_report_number_bugtracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtracker',
            name='assigned_to',
            field=models.CharField(choices=[('group', 'Group'), ('manager', 'Manager')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='comments',
            field=models.TextField(default='comment'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='functional_area',
            field=models.CharField(choices=[('database', 'Database'), ('network', 'Network'), ('application', 'Application'), ('front_end', 'Front End'), ('deployment', 'Deployment'), ('fatal', 'Fatal')], default='database', max_length=20),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='priority',
            field=models.CharField(choices=[('Fix immediately', 'Immediately - 1'), ('Fix as soon as possible', 'ASAP - 2'), ('Fix before next milestone', 'Before Next Milestone - 3'), ('Fix before release', 'Before Release - 4'), ('Fix if possible', 'If Possible - 5'), ('Optional', 'Optional - 6')], default='optional', max_length=100),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='problem',
            field=models.TextField(default='problem'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='reproducible',
            field=models.TextField(default='NO'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='resolution',
            field=models.CharField(choices=[('pending', 'Pending'), ('fixed', 'Fixed'), ('irreproducible', 'Irreproducible'), ('deferred', 'Deferred'), ('as designed', 'As Designed'), ('cannot be fixed', 'Cannot be fixed'), ('withdrawn by reported', 'Withdrawn by Reporter'), ('need more info', 'Need More Info'), ('disagree with suggestion', 'Disagree with Suggestion')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='resolution_version',
            field=models.CharField(choices=[('Fix immediately', 'Immediately'), ('Fix as soon as possible', 'ASAP'), ('Fix before next milestone', 'Before Next Milestone'), ('Fix before release', 'Before Release'), ('Fix if possible', 'If Possible'), ('Optional', 'Optional')], default='1.0', max_length=100),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='resolved_by',
            field=models.CharField(choices=[('Fix immediately', 'Immediately'), ('Fix as soon as possible', 'ASAP'), ('Fix before next milestone', 'Before Next Milestone'), ('Fix before release', 'Before Release'), ('Fix if possible', 'If Possible'), ('Optional', 'Optional')], default='abc@bughound.com', max_length=100),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='resolved_date',
            field=models.DateField(default='2022-07-15'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='suggested_fix',
            field=models.TextField(default='code'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='tested_by',
            field=models.CharField(choices=[('Fix immediately', 'Immediately'), ('Fix as soon as possible', 'ASAP'), ('Fix before next milestone', 'Before Next Milestone'), ('Fix before release', 'Before Release'), ('Fix if possible', 'If Possible'), ('Optional', 'Optional')], default='abc@bughound.com', max_length=100),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='tested_date',
            field=models.DateField(default='2022-07-15'),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='treated_as_deferred',
            field=models.TextField(default='NO'),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='date',
            field=models.DateField(default='2022-07-15'),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='problem_summary',
            field=models.TextField(default='summary'),
        ),
    ]
