# Generated by Django 4.0.6 on 2022-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_bugtracker_assigned_to_bugtracker_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='assigned_to',
            field=models.CharField(choices=[('Group', 'Group'), ('Manager', 'Manager')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='functional_area',
            field=models.CharField(choices=[('Database', 'Database'), ('Network', 'Network'), ('Application', 'Application'), ('Front End', 'Front End'), ('Deployment', 'Deployment'), ('Fatal', 'Fatal')], default='database', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='program',
            field=models.CharField(choices=[('VS Code', 'VS Code'), ('Pycharm', 'Pycharm'), ('Sublime Text', 'Sublime Text'), ('SQL Server', 'SQL Server'), ('Notepad ++', 'Notepad ++'), ('Outlook', 'Outlook')], default='vscode', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='report_type',
            field=models.CharField(choices=[('Coding Error', 'Coding Error'), ('Design Issue', 'Design Issue'), ('Suggestion', 'Suggestion'), ('Documentation', 'Documentation'), ('Hardware', 'Hardware'), ('Query', 'Query')], default='coding_error', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='reported_by',
            field=models.CharField(choices=[('Praneeth', 'Praneeth'), ('Shruthi', 'Shruthi')], default='praneeth', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='resolution',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed'), ('Irreproducible', 'Irreproducible'), ('Deferred', 'Deferred'), ('As Designed', 'As Designed'), ('Cannot be fixed', 'Cannot be fixed'), ('Withdrawn by Reporter', 'Withdrawn by Reporter'), ('Need More Info', 'Need More Info'), ('Disagree with Suggestion', 'Disagree with Suggestion')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='severity',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Infectious', 'Infectious'), ('Minor', 'Minor'), ('Serious', 'Serious'), ('Fatal', 'Fatal')], default='mild', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
