# Generated by Django 3.2.14 on 2022-07-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0006_auto_20220718_0241'),
        ('bugtracker', '0010_remove_bugtracker_attachment'),
    ]

    operations = [
    ]
