# Generated by Django 4.0.6 on 2022-07-28 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0010_remove_bugtracker_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtracker',
            name='attachment',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
