# Generated by Django 3.2.14 on 2022-07-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0011_bugtracker_attachment'),
        ('bugtracker', '0011_merge_20220728_0129'),
    ]

    operations = [
    ]
