# Generated by Django 3.2.14 on 2022-07-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0012_merge_20220728_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugtracker',
            name='release',
            field=models.CharField(default='rel_01', max_length=20),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='assigned_to',
            field=models.CharField(choices=[('Group', 'Group'), ('Manager', 'Manager')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='functional_area',
            field=models.CharField(choices=[('Database', 'Database'), ('Network', 'Network'), ('Application', 'Application'), ('Front End', 'Front End'), ('Deployment', 'Deployment'), ('Fatal', 'Fatal')], default='database', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='resolution',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed'), ('Irreproducible', 'Irreproducible'), ('Deferred', 'Deferred'), ('As Designed', 'As Designed'), ('Cannot be fixed', 'Cannot be fixed'), ('Withdrawn by Reporter', 'Withdrawn by Reporter'), ('Need More Info', 'Need More Info'), ('Disagree with Suggestion', 'Disagree with Suggestion')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='resolved_by',
            field=models.CharField(choices=[('abc@bughound.com', 'abc@bughound.com'), ('def@bughound.com', 'def@bughound.com')], default='abc@bughound.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='tested_by',
            field=models.CharField(choices=[('abc@bughound.com', 'abc@bughound.com'), ('def@bughound.com', 'def@bughound.com')], default='abc@bughound.com', max_length=100),
        ),
    ]
