# Generated by Django 3.2.14 on 2022-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0013_auto_20220729_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('loginID', models.TextField()),
                ('level', models.CharField(choices=[('lowest', '1'), ('second highest', '2'), ('highest', '3')], default='1', max_length=20)),
            ],
        ),
    ]
