# Generated by Django 3.2.14 on 2022-08-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0017_auto_20220810_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program',
            new_name='name',
        ),
    ]
