# Generated by Django 3.2.14 on 2022-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0018_rename_program_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='loginID',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
