# Generated by Django 3.2.14 on 2022-08-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0019_auto_20220810_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtracker',
            name='program',
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='program',
            field=models.ManyToManyField(to='bugtracker.Program'),
        ),
    ]
