# Generated by Django 3.2.14 on 2022-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0020_auto_20220810_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtracker',
            name='program',
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='program',
            field=models.CharField(choices=[('VS Code', 'VS Code'), ('Pycharm', 'Pycharm'), ('Sublime Text', 'Sublime Text'), ('SQL Server', 'SQL Server'), ('Notepad ++', 'Notepad ++'), ('Outlook', 'Outlook')], default='vscode', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='loginID',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
