# Generated by Django 3.2.14 on 2022-08-11 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0022_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.program'),
        ),
    ]
