# Generated by Django 3.2.14 on 2022-08-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0023_auto_20220811_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='program',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='bugtracker.program'),
        ),
    ]
