# Generated by Django 3.2.14 on 2022-08-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0024_alter_area_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugtracker.program'),
        ),
    ]
