# Generated by Django 4.0.6 on 2022-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0025_alter_bugtracker_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='release',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='version',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
